/**
 * CDK stack definition for a Dokploy-managed static site.
 *
 * Provisions:
 *   - S3 bucket with public-read static website hosting
 *   - CloudFront distribution (HTTP/2, HTTPS redirect, SPA 403→200 fallback,
 *     CachingOptimized policy, PriceClass_100)
 *
 * Route 53 records are NOT included here because hosted-zone discovery
 * requires live AWS API calls at synthesis time. They are created separately
 * via the Route 53 SDK after the stack outputs are known.
 *
 * Usage:
 *   const templateBody = synthesizeStaticSiteTemplate({ stackName, bucketName, region });
 *   // → JSON CloudFormation template ready to pass to CreateStack / UpdateStack
 */

import { tmpdir } from "node:os";
import { join } from "node:path";
import * as cdk from "aws-cdk-lib";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as cfOrigins from "aws-cdk-lib/aws-cloudfront-origins";
import * as s3 from "aws-cdk-lib/aws-s3";
import type { Construct } from "constructs";

// ---------------------------------------------------------------------------
// Stack props
// ---------------------------------------------------------------------------

interface StaticSiteProps extends cdk.StackProps {
	/** Pre-determined S3 bucket name (auto-generated by Dokploy if not user-supplied). */
	bucketName: string;
}

// ---------------------------------------------------------------------------
// CDK Stack
// ---------------------------------------------------------------------------

class StaticSiteStack extends cdk.Stack {
	constructor(scope: Construct, id: string, props: StaticSiteProps) {
		super(scope, id, props);

		// ── S3 Bucket ──────────────────────────────────────────────────────────
		const bucket = new s3.Bucket(this, "SiteBucket", {
			bucketName: props.bucketName,
			websiteIndexDocument: "index.html",
			websiteErrorDocument: "index.html", // SPA fallback
			publicReadAccess: true,
			// Allow public bucket policies while blocking public ACLs
			blockPublicAccess: new s3.BlockPublicAccess({
				blockPublicAcls: false,
				blockPublicPolicy: false,
				ignorePublicAcls: false,
				restrictPublicBuckets: false,
			}),
			// Keep the bucket if the stack is deleted (preserve user data)
			removalPolicy: cdk.RemovalPolicy.RETAIN,
		});

		// ── CloudFront Distribution ────────────────────────────────────────────
		const distribution = new cloudfront.Distribution(this, "SiteDistribution", {
			defaultRootObject: "index.html",
			defaultBehavior: {
				// Point to the S3 website endpoint (HTTP-only origin)
				origin: new cfOrigins.HttpOrigin(bucket.bucketWebsiteDomainName, {
					protocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
				}),
				viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
				cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
				allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD,
				compress: true,
			},
			// Map S3's 403 (missing key) → 200 with index.html for SPA routing
			errorResponses: [
				{
					httpStatus: 403,
					responseHttpStatus: 200,
					responsePagePath: "/index.html",
					ttl: cdk.Duration.seconds(0),
				},
			],
			priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
			httpVersion: cloudfront.HttpVersion.HTTP2,
		});

		// ── Stack Outputs (read back after deployment) ─────────────────────────
		new cdk.CfnOutput(this, "BucketName", {
			value: bucket.bucketName,
			description: "S3 bucket name",
		});
		new cdk.CfnOutput(this, "DistributionId", {
			value: distribution.distributionId,
			description: "CloudFront distribution ID",
		});
		new cdk.CfnOutput(this, "CloudFrontDomain", {
			value: distribution.distributionDomainName,
			description: "CloudFront domain name (e.g. d1abc.cloudfront.net)",
		});
	}
}

// ---------------------------------------------------------------------------
// Synthesis helper
// ---------------------------------------------------------------------------

/**
 * Synthesize the static-site CDK stack to a CloudFormation template JSON
 * string, without touching disk or requiring the CDK CLI.
 *
 * The resulting string can be passed directly to the CloudFormation
 * `CreateStack` / `UpdateStack` API as `TemplateBody`.
 */
export function synthesizeStaticSiteTemplate(params: {
	/** CloudFormation stack name (must match [A-Za-z][-A-Za-z0-9]*). */
	stackName: string;
	/** S3 bucket name to create. */
	bucketName: string;
}): string {
	const app = new cdk.App({ outdir: join(tmpdir(), "cdk-dokploy-synth") });

	new StaticSiteStack(app, params.stackName, {
		// Environment-agnostic: region/account resolved by CloudFormation at
		// deploy time via AWS::Region / AWS::AccountId pseudo-parameters.
		bucketName: params.bucketName,
	});

	const assembly = app.synth();
	const stack = assembly.stacks[0];

	if (!stack) {
		throw new Error("CDK synthesis produced no stacks");
	}

	return JSON.stringify(stack.template);
}
